### ISSUE TITLE
Does it support recursive functions?

### ISSUE THREAD

**Issue by dengzhicong** [pkujhd/goloader#100]
I found that recursive calls fail
![PixPin_2024-07-03_17-31-01](https://github.com/pkujhd/goloader/assets/9531135/a4f7233c-9bbc-4959-93da-2893badfc4c5)
![PixPin_2024-07-03_17-31-28](https://github.com/pkujhd/goloader/assets/9531135/cd4f8a10-0cb2-48e8-b460-db942d654a84)

**Comment by pkujhd** [comment]
@dengzhicong  
in your case. you just read objects, but not Load, Load function will relocate symbol and get position for symbol.

**Comment by dengzhicong** [comment]
Sorry, it was an internal error in this function
`goloader.Load(linker, symPtr)`
![PixPin_2024-07-03_18-05-38](https://github.com/pkujhd/goloader/assets/9531135/86b0da53-7979-48ef-9a4a-37bdab90ef69)

**Comment by dengzhicong** [comment]
`package main

import (
	"fmt"
	"os"
	"unsafe"

	"github.com/pkujhd/goloader"
)

func main() {
	linker, err := goloader.ReadObjs([]string{"goloader.o"}, []string{"main"})
	if err != nil {
		panic(err)
	}

	run := "main.RandInt"

	symPtr := make(map[string]uintptr)
	err = goloader.RegSymbol(symPtr)

	if err != nil {
		panic(err)
	}

	codeModule, err := goloader.Load(linker, symPtr)
	if err != nil {
		panic(err)
	}

	a := linker.SymMap["go-plugin-benchmark/fib.tailRecursiveFibonacci"]
	if a != nil {
		fmt.Println(a)
	}

	runFuncPtr, ok := codeModule.Syms[run]
	if !ok || runFuncPtr == 0 {
		fmt.Println("Load error! not find function:", run)
		return
	}
	funcPtrContainer := (uintptr)(unsafe.Pointer(&runFuncPtr))
	runFunc := *(*func() int)(unsafe.Pointer(&funcPtrContainer))
	result := runFunc()
	fmt.Println("result:{}", result)

	os.Stdout.Sync()
	codeModule.Unload()
}
`

fib
`package fib

func tailRecursiveFibonacci(n, a, b int) int {
	if n == 0 {
		return a
	}
	if n == 1 {
		return b
	}

	return tailRecursiveFibonacci(n-1, b, (a+b)%1000000007)
}

func FibonacciRecursive(n int) int {
	return tailRecursiveFibonacci(n, 0, 1)
}
`

**Comment by dengzhicong** [comment]
`
package fib

func tailRecursiveFibonacci(n, a, b int) int {
	if n == 0 {
		return a
	}
	if n == 1 {
		return b
	}

	return tailRecursiveFibonacci(n-1, b, (a+b)%1000000007)
}

func FibonacciRecursive(n int) int {
	return tailRecursiveFibonacci(n, 0, 1)
}

=======================================

package main

import (
	"fmt"
	"os"
	"unsafe"
	"github.com/pkujhd/goloader"
)

func main() {
	linker, err := goloader.ReadObjs([]string{"goloader.o"}, []string{"main"})
	if err != nil {
		panic(err)
	}

	run := "main.RandInt"

	symPtr := make(map[string]uintptr)
	err = goloader.RegSymbol(symPtr)

	if err != nil {
		panic(err)
	}

	codeModule, err := goloader.Load(linker, symPtr)
	if err != nil {
		panic(err)
	}

	a := linker.SymMap["go-plugin-benchmark/fib.tailRecursiveFibonacci"]
	if a != nil {
		fmt.Println(a)
	}

	runFuncPtr, ok := codeModule.Syms[run]
	if !ok || runFuncPtr == 0 {
		fmt.Println("Load error! not find function:", run)
		return
	}
	funcPtrContainer := (uintptr)(unsafe.Pointer(&runFuncPtr))
	runFunc := *(*func() int)(unsafe.Pointer(&funcPtrContainer))
	result := runFunc()
	fmt.Println("result:{}", result)

	os.Stdout.Sync()
	codeModule.Unload()
}



`

**Comment by eh-steve** [comment]
Seems ok on my fork… 
https://github.com/eh-steve/goloader/commit/88d85dba9ea882c36aef678a0acbf4ffac167cb5

**Comment by pkujhd** [comment]
> Seems ok on my fork… [eh-steve@88d85db](https://github.com/eh-steve/goloader/commit/88d85dba9ea882c36aef678a0acbf4ffac167cb5)

i test eh-steve's case, my repos is ok too.

@dengzhicong  please provide a reproducible case

**Comment by dengzhicong** [comment]
This is my test code

https://github.com/dengzhicong/go-plugin-benchmark

**Comment by pkujhd** [comment]
you may use eh-steve's fork, this fork auto load dependent library.

**Comment by dengzhicong** [comment]
ok. Thank You
