### ISSUE TITLE
about encoding/json panic

### ISSUE THREAD

**Issue by ljh951028** [pkujhd/goloader#20]
i used this goloader load a go (.o) file and run a function ,this function used encoding/json package to encoding string,when i run this function, produce a panic:
--- FAIL: Test_load (1.14s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x5918e5]

goroutine 6 [running]:
testing.tRunner.func1.1(0x68acc0, 0x86f360)
	D:/go/Go/src/testing/testing.go:988 +0x516
testing.tRunner.func1(0xc000128360)
	D:/go/Go/src/testing/testing.go:991 +0x31e
panic(0x68acc0, 0x86f360)
	D:/go/Go/src/runtime/panic.go:975 +0x429
encoding/json.(*encodeState).marshal.func1(0xc000167a70)
	D:/go/Go/src/encoding/json/encode.go:326 +0x111
panic(0x68acc0, 0x86f360)
	D:/go/Go/src/runtime/panic.go:975 +0x429
encoding/json.(*encodeState).string(0xc0000a4000, 0x0, 0x300000005, 0x1)
	D:/go/Go/src/encoding/json/encode.go:1004 +0xa5
encoding/json.stringEncoder(0xc0000a4000, 0x67a3a0, 0xc0001e0000, 0x98, 0x100)
	D:/go/Go/src/encoding/json/encode.go:645 +0x47c
encoding/json.structEncoder.encode(0xc0000b2000, 0x7, 0x8, 0xc0000a2120, 0xc0000a4000, 0x1320750, 0xc0001e0000, 0x99, 0x710100)
	D:/go/Go/src/encoding/json/encode.go:759 +0x3fa
encoding/json.(*encodeState).reflectValue(0xc0000a4000, 0x1320750, 0xc0001e0000, 0x99, 0x100)
	D:/go/Go/src/encoding/json/encode.go:358 +0x86
encoding/json.(*encodeState).marshal(0xc0000a4000, 0x1320750, 0xc0001e0000, 0x100, 0x0, 0x0)
	D:/go/Go/src/encoding/json/encode.go:330 +0xe9
encoding/json.Marshal(0x1320750, 0xc0001e0000, 0x0, 0x0, 0x0, 0x0, 0x0)
	D:/go/Go/src/encoding/json/encode.go:161 +0xa4
main.get_meta(0x689220, 0xc00006ef90)
	E:/Workspace/R2/collide-engine/internal/engine/engine.go:9 +0x5c
collie-engine/internal/loader.(*rule).load(0xc000051e9f, 0x6ddcb2, 0x19, 0x0, 0x0)
	e:/Workspace/R2/collide-engine/internal/loader/loader.go:74 +0x60a
collie-engine/internal/loader.Test_load(0xc000128360)
	e:/Workspace/R2/collide-engine/internal/loader/loader_test.go:7 +0x4b
testing.tRunner(0xc000128360, 0x6e60e0)
	D:/go/Go/src/testing/testing.go:1039 +0x191
created by testing.(*T).Run
	D:/go/Go/src/testing/testing.go:1090 +0x6be
Process exiting with code: 0

**Comment by pkujhd** [comment]
please give me a testcase, i will try to reappear it
