### ISSUE TITLE
Could it possible to be a scripting engine?

### ISSUE THREAD

**Issue by zhengzepeng** [pkujhd/goloader#23]
Could it possible to be a scripting engine?the script compile in the runtime and run it?

**Comment by pkujhd** [comment]
you could try https://github.com/cosmos72/gomacro.
if you want it like lua or javascript, it will be a big project

**Comment by zhengzepeng** [comment]
> you could try https://github.com/cosmos72/gomacro.
> if you want it like lua or javascript, it will be a big project

Thanks!
