### ISSUE TITLE
loader 是so调用 函数失败

### ISSUE THREAD

**Issue by tooBugs** [pkujhd/goloader#24]
loader 是so加载.o文件成功但是掉用 .o文件函k数失败了，loader可以是so吗？

**Comment by pkujhd** [comment]
你想说的是你的loader是一个动态库，是用plugin加载的？然后用loader加载一个.o?

**Comment by tooBugs** [comment]
我想测试把loader用c-shard编译成so，然后注入到其他程序中加载.o，但是这样调用失败了

**Comment by pkujhd** [comment]
你想编译成C的.so，然后让C程序加载.so，然后去读取一个go的.o 执行？把错误贴出来吧

**Comment by tooBugs** [comment]
是的，直接在.o文件函数的时候失败了，运行runFunc() 不能成功执行.o文件里的函数，loader也不往下执行了，没有错误！

**Comment by pkujhd** [comment]
> 是的，直接在.o文件函数的时候失败了，运行runFunc() 不能成功执行.o文件里的函数，loader也不往下执行了，runFunc()没有错误返回！
给一个你错误的工程.

**Comment by tooBugs** [comment]
package main

import (
  "io/ioutil"
 )
 
func MyTest() {
         ioutil.WriteFile("/tmp/1234", []byte(""), 0666)
}

我把上面的代码编译成o文件，让loader编译的so加载该o文件掉用函数main.MyTest()失败了。（我修改了exe, err := os.Executable()了这个获取exe的路径，让其获取我的so路径，这样注册符号那些就成功了，但是掉用main.MyTest失败）

**Comment by pkujhd** [comment]
你的loader是如何编译的，loader不是让C++去用dlopen调用的么？有完整的测试工程的话，发一个出来，需要复现错误

**Comment by tooBugs** [comment]
unexpected fault address 0x7fa25e925762
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fa25e925762 pc=0x404f9000]

goroutine 17 [running, locked to thread]:
runtime.throw(0x7fa215b8d4c0, 0x5)
	/usr/local/go/src/runtime/panic.go:605 +0x97 fp=0xc420049218 sp=0xc4200491f8 pc=0x7fa2158e8377
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x22b fp=0xc420049268 sp=0xc420049218 pc=0x7fa2158fe51b
main.MyTest2()
	/root/elfloader/src/goloader/examples/testnil/testnil.go:7 fp=0xc420049270 sp=0xc420049268 pc=0x404f9000
main.mytest1()
	/root/elfloader/src/goloader/examples/loader/loader.go:98 +0x123e fp=0xc420049e98 sp=0xc420049270 pc=0x7fa215b8a5fe
main._cgoexpwrap_815366bb35a3_mytest1()
	command-line-arguments/_obj/_cgo_gotypes.go:45 +0x22 fp=0xc420049ea8 sp=0xc420049e98 pc=0x7fa215b893a2
runtime.call32(0x0, 0x7fffd19a7508, 0x7fffd19a75af, 0x0)
	/usr/local/go/src/runtime/asm_amd64.s:509 +0x3d fp=0xc420049ed8 sp=0xc420049ea8 pc=0x7fa215913ccd
runtime.cgocallbackg1(0x0)
	/usr/local/go/src/runtime/cgocall.go:305 +0x1a0 fp=0xc420049f58 sp=0xc420049ed8 pc=0x7fa2158bf030
runtime.cgocallbackg(0x0)
	/usr/local/go/src/runtime/cgocall.go:187 +0x95 fp=0xc420049fc0 sp=0xc420049f58 pc=0x7fa2158bedf5
runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/asm_amd64.s:762 +0x9a fp=0xc420049fe0 sp=0xc420049fc0 pc=0x7fa2159152da
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420049fe8 sp=0xc420049fe0 pc=0x7fa215916531

报了这个错误

**Comment by tooBugs** [comment]
main.mytest1() 是我loader的导出函数，main.MyTest2()是我o文件的函数

**Comment by tooBugs** [comment]
loader里加入
import "C"

//export mytest1
然后 go build buildmode=c-shared -o libloader.so loader.go

**Comment by tooBugs** [comment]
请问是否能重现错误，如果不能重现，我抽空整理下测试代码？

**Comment by pkujhd** [comment]
我能看到的错误，就是Loader返回了错误，os.WriteFile没有找到， 如果无视这个错误, 程序就会崩掉，但是和你提供的error不同

**Comment by tooBugs** [comment]
这个错误是因为path找的是elf文件的路径，我是把os.Executable() 这里强制修改了，强制修改成loader.so的绝对路径，这样load注册函数就不会返回错误了，exe="/tmp/loader.so",这样就没有这个错误了。您可以试一下

**Comment by pkujhd** [comment]
@tooBugs 
你用的方案里是有问题，因为读不到全局变量地址。这个错误我在看代码的时候就已经知道了，比如os.stdout就找不到地址

但是你给我的testcase里，我测不出这种情况，因为编译出来的那个.o刚好不用啥全局变量

**Comment by tooBugs** [comment]
是我不能 把os.Executable()这里修改成loader.so的绝对路径吗？这样会造成全局变量地址reloc失败，我编译的o文件里也没有全局变量的，我只是把loader.so里的os.Executable修改成 我loader.so本身的绝对路径，这样就不会出现unresolve external这个问题。即把register.go 里面exe, err := os.Executable()替换成exe="/tmp/loader.so"。不可以这样吗？

**Comment by tooBugs** [comment]
是不是 必须是ELF的路径才行？

**Comment by pkujhd** [comment]
并不是你些的golang的代码中没有全局变量就是没有的，比如fmt.Println(xxx), 这个实际会使用os.Stdout。

当前的版本RegSymbol会调用os.Executable()得到当前程序的path，在你的环境里，会读到的是加载loader.so的ELF的C/C++编译的程序的path，这个里边是没有golang运行的符号表的，当你把他改成loader.so的path的时候，就正常了
这里使用绝对路径和相对路径都是可以的.

**Comment by pkujhd** [comment]
> 是不是 必须是ELF的路径才行？

不能是ELF的路径，应为这个是C/C++编译的，里边只有C/C++的符号表

**Comment by tooBugs** [comment]
是的 我已经把os.Executable()修改了成loader.so的path了，注册函数这些都是没问题了，也找到o文件的函数地址了，就是不能调用该函数，我也在内存里看了，该地址确实是o文件函数的地址

**Comment by pkujhd** [comment]
为啥会不能调用这个函数呢？你想表达的是不能在C里边调用golang的函数？在loader里边调用是没有问题的，可以正常执行

**Comment by tooBugs** [comment]
我的想法是能够让loader编译成.so，这样我C的代码就可以加载该loader.so，从而再让loader.so加载o文件并执行里面的函数。能支持这种情况吗？

**Comment by pkujhd** [comment]
> 我的想法是能够让loader编译成.so，这样我C的代码就可以加载该loader.so，从而再让loader.so加载o文件并执行里面的函数。能支持这种情况吗？

这样是可行的，我已经测试过了，可以正常执行，需要修改RegSymbol，让他去读loader.so的symbol就可以了.

**Comment by pkujhd** [comment]
pkujhd@pkujhd a % cat 1.cpp 
#include <stdio.h>  
#include <dlfcn.h>  
  
int main(int argc, char **argv) {  
	void *handle;  
	void (*cosine)();
	char *error;  
  
	handle = dlopen ("../dlloader", RTLD_LAZY);
	if (!handle) {  
		fprintf (stderr, "%s \n", dlerror());
	}  
  
	cosine = (void(*)())dlsym(handle, "loader");
	if ((error = dlerror()) != NULL)  {  
		fprintf (stderr, "%s \n", error);
		return 0;
	}  
  
	(*cosine)();
	dlclose(handle);  
	return 0;  
}  
pkujhd@pkujhd a % g++ 1.cpp -l dl
pkujhd@pkujhd a % cat 1.go
package main

import (
	"fmt"
	"io/ioutil"
)
func main() {
	fmt.Println("WWWW")
	ioutil.WriteFile("./1234", []byte(""), 0666)
}
pkujhd@pkujhd a % go tool compile 1.go
pkujhd@pkujhd a % ls -l
total 144
-rw-r--r--  1 pkujhd  staff    439  4  1 11:51 1.cpp
-rw-r--r--  1 pkujhd  staff    128  4  1 13:47 1.go
-rw-r--r--  1 pkujhd  staff   8488  4  1 16:32 1.o
-rwxr-xr-x  1 pkujhd  staff  49656  4  1 16:31 a.out
pkujhd@pkujhd a % ./a.out 
WWWW
pkujhd@pkujhd a % 
pkujhd@pkujhd a % ls -l
total 144
-rw-r--r--  1 pkujhd  staff    439  4  1 11:51 1.cpp
-rw-r--r--  1 pkujhd  staff    128  4  1 13:47 1.go
-rw-r--r--  1 pkujhd  staff   8488  4  1 16:32 1.o
-rw-r--r--  1 pkujhd  staff      0  4  1 16:32 1234
-rwxr-xr-x  1 pkujhd  staff  49656  4  1 16:31 a.out
pkujhd@pkujhd a %

**Comment by tooBugs** [comment]
RegSymbol只修改path成loader.so的路径是吗？没有其他修改了吧，我再golang 1.9的情况下还是不行，请问您那边是golang哪个版本

**Comment by pkujhd** [comment]
我是在macosx上的golang1.16.2上测试的，你的有问题的话，告知下我你的测试环境

**Comment by tooBugs** [comment]
我的golang版本 是1.9  在centos6 x64上运行

**Comment by pkujhd** [comment]
> 我的golang版本 是1.9 在centos6 x64上运行

Linux上在编译.so的时候将赋值TLS的语句改写了，所以函数头出问题了

**Comment by pkujhd** [comment]
替换下regTLS函数，应该可以了，但是只能在Linux上用
```
func regTLS(symPtr map[string]uintptr, offset int) {
	funcptr := getFunctionPtr(regTLS)
	tlsptr := *(*uint32)(adduintptr(funcptr, offset-2))
	tlsptr = *(*uint32)(adduintptr(funcptr, (int)(tlsptr) + 7))
	symPtr[TLSNAME] = uintptr(tlsptr)
}
```

**Comment by tooBugs** [comment]
是的，非常感谢。已经可以了，我打算把源码了解的更深入些，请问有相关资料或说明吗？

**Comment by pkujhd** [comment]
> 是的，非常感谢。已经可以了，我打算把源码了解的更深入些，请问有相关资料或说明吗？

基本没有，只能读golang源代码的linker，因为本质上就是一个dl.

**Comment by pkujhd** [comment]
@tooBugs , https://github.com/pkujhd/goloader/commit/7701df1d3cfffd85c5f004287cf8073a54f1d954 already support loader is a dynamic library.
