### ISSUE TITLE
go中小写的未定义符号如何注册

### ISSUE THREAD

**Issue by ssrlxl** [pkujhd/goloader#26]
unresolve external:github.com/klauspost/compress/flate.crc32sse
unresolve external:runtime/debug.modinfo
unresolve external:runtime.walltime1
unresolve external:runtime.panicSlice3CU
unresolve external:github.com/klauspost/cpuid.asmCpuidex
unresolve external:github.com/klauspost/crc32.haveSSE42
unresolve external:internal/reflectlite.ifaceE2I
unresolve external:hash/crc32.castagnoliSSE42
unresolve external:reflect.rselect
unresolve external:os.fastrand
unresolve external:reflect.typehash
unresolve external:github.com/Yawning/chacha20.xgetbv0Amd64
unresolve external:reflect.makechan
unresolve external:github.com/klauspost/compress/flate.histogram
unresolve external:runtime/debug.setPanicOnFault
unresolve external:runtime/debug.freeOSMemory
unresolve external:runtime.profileloop
unresolve external:runtime.breakpoint

上面未定义的符号还小写的，这种如何注册

**Comment by pkujhd** [comment]
给出个case，现在的描述没法知道你是怎么处理的
