### ISSUE TITLE
函数需要传递参数或者返回数据会崩溃

### ISSUE THREAD

**Issue by ssrlxl** [pkujhd/goloader#27]
我的main.go是这样的函数类型
var initFunc func(string)
var setPicInfoFunc func(string)
var getPicInfoFunc func() string
调用后崩溃
![image](https://user-images.githubusercontent.com/3366782/119789737-e99c2c00-bf05-11eb-9d22-1f6c2860f46b.png)
![image](https://user-images.githubusercontent.com/3366782/119789966-19e3ca80-bf06-11eb-8122-0f90cda2103e.png)

**Comment by pkujhd** [comment]
@ssrlxl 无法复现你的错误，请给出完整的case

**Comment by ssrlxl** [comment]
> @ssrlxl 无法复现你的错误，请给出完整的case， 以及所使用的go版本，运行环境
是我封装的问题，地址引用错误
