### ISSUE TITLE
如何注册os.Args 和 runtime.block

### ISSUE THREAD

**Issue by ParkourLiu** [pkujhd/goloader#28]

**Comment by ParkourLiu** [comment]
![image](https://user-images.githubusercontent.com/33681340/120459045-6463bc00-c3ca-11eb-8b7c-7b8668e23da1.png)

**Comment by pkujhd** [comment]
@ParkourLiu  这是你没有调用goloader.RegSymbol(symPtr)  或者就是你的加载器是一个.so

**Comment by ParkourLiu** [comment]
我已经调用了goloader.RegSymbol(symPtr)，只不过我是静态编译的。编译命令是go build -ldflags "-s -w -extldflags '-static'"。直接使用go build出来的loader是可以运行的。但是静态编译的loader就报unresolve external:runtime.algarray

**Comment by ParkourLiu** [comment]
![image](https://user-images.githubusercontent.com/33681340/120618007-398e6c00-c48d-11eb-86b6-78e883646058.png)
通过排查发现，使用静态编译的时候，这一行 syms, err := f.Symbols() 返回的是一个空的数组，并且返回错误 no symbol section

**Comment by ParkourLiu** [comment]
解决了，编译时不能加 -s -w  参数

**Comment by pkujhd** [comment]
> -s -w

这个参数会把所有的符号信息都清除掉

**Comment by ParkourLiu** [comment]
学到了。。谢谢大佬
