### ISSUE TITLE
当使用select{}关键字的时候，无法注册runtime.block

### ISSUE THREAD

**Issue by ParkourLiu** [pkujhd/goloader#29]
当我代码中使用了select时。会报 unresolve external:runtime.block

**Comment by ParkourLiu** [comment]
package main

import (
	"fmt"
	"time"
)

func main() {
	for _, v := range []int{1, 2, 3, 4, 5} {
		go func(v int) {
			for {
				time.Sleep(time.Second)
			}
		}(v)
	}
	fmt.Println(11)
	select {}
}

**Comment by ParkourLiu** [comment]
以上代码。使用goloader加载运行时，因为select{}  ,会报错unresolve external:runtime.block

**Comment by ParkourLiu** [comment]
还有使用了第三方库里面。。应该也是有哪个关键字吧。。。会报unresolve external:runtime.chanrecv2

**Comment by pkujhd** [comment]
> 以上代码。使用goloader加载运行时，因为select{} ,会报错unresolve external:runtime.block

你要在动态时候使用select的特性，则需要loader也使用，这样运行时才有这个函数符号，因为这个是go的系统内部函数，所以无法使用register来注册它

例如这个runtime.block 你需要在loader里边也有select{}

**Comment by ParkourLiu** [comment]
runtime.chanrecv2是什么没有注册进去呢？搜索出来是chan的底层会用到runtime.chanrecv2，可是我在loader中声明并初始化了一个chan后，还是报这个错误

**Comment by pkujhd** [comment]
> runtime.chanrecv2是什么没有注册进去呢？搜索出来是chan的底层会用到runtime.chanrecv2，可是我在loader中声明并初始化了一个chan后，还是报这个错误

只声明没有用，需要使用这个channel， 应该recv一下就会底层用到runtime.chanrecv2这个函数

**Comment by ParkourLiu** [comment]
c := make(chan bool, 2)
	c <- true
	v, ok := <-c
	fmt.Println(v, ok)
调试下来发现，使用v := <-c还是会报runtime.chanrecv2，必须使用第三行的v, ok := <-c，底层才会调用runtime.chanrecv2这个函数，才不会报错了。。。谢谢大神指点！
