### ISSUE TITLE
当使用upx压缩loader时，会如下报错。。怎么能够保证我使用upx后还可以正常使用goloader呢？

### ISSUE THREAD

**Issue by ParkourLiu** [pkujhd/goloader#30]
![image](https://user-images.githubusercontent.com/33681340/121142330-759b4580-c86e-11eb-984e-95a439969f1b.png)

**Comment by pkujhd** [comment]
@ParkourLiu  无法使用，这类的软件都会在开始时做strip操作，抹掉符号表

**Comment by pkujhd** [comment]
你要使用upx或者类似的东西的话，只能用golang自带的plugin，它编译出来的.so会自带runtime

**Comment by pkujhd** [comment]
@ParkourLiu P， 倒是可以这么干，把原先的文件产生一个符号表，生成一个配置文件，然后注册的时候就调用那个，不在使用register函数，案例说生成的那个map的文件应该不大。只是打包的流程变复杂了，另外发布的文件变多了
