### ISSUE TITLE
android 编译一些符号找不到

### ISSUE THREAD

**Issue by ssrlxl** [pkujhd/goloader#31]
我用android编译： GOOS=android GOARCH=arm64 CGO_ENABLED=0 CC=/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android22-clang go build -v

runtime.writeBarrier
os.Stdout 符号找不到

**Comment by pkujhd** [comment]
@ssrlxl , android环境未进行测试，不过按理来说它和linux arm64 应该是一致的， 检查下你的编译是否strip了符号表

**Comment by ssrlxl** [comment]
> @ssrlxl , android环境未进行测试，不过按理来说它和linux arm64 应该是一致的， 检查下你的编译是否strip了符号表

现在对了，是strip的影响，但是我用例子里的http.go 会崩溃，在linux是正常的，为android下回崩溃
![image](https://user-images.githubusercontent.com/3366782/121340652-6c83a480-c952-11eb-8e34-a70300b543db.png)

**Comment by pkujhd** [comment]
给我复制一个完整的栈，另外告知下系统版本，golang版本， goloader使用的版本. 
我手头没有现成的android环境，不一定能支持

**Comment by ssrlxl** [comment]
go: 1.16.2
android : 7.1
goloader : 最新版本

unexpected fault address 0xc61f5c00
unexpected fault address 0xc61d6220
fatal error: fault
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc61d6220 pc=0x2aaac5ee7668]

goroutine 8 [running]:
runtime.throw(0x2aaac612065e, 0x5)
        /go/src/runtime/panic.go:1117 +0x4c fp=0x4000031720 sp=0x40000316f0 pc=0x2aaac5f0c18c
runtime.sigpanic()
        /go/src/runtime/signal_unix.go:741 +0x228 fp=0x4000031760 sp=0x4000031720 pc=0x2aaac5f21aa8
runtime.newobject(0xc61d6220, 0x0)
        /go/src/runtime/malloc.go:1177 +0x18 fp=0x40000317a0 sp=0x4000031770 pc=0x2aaac5ee7668
fatal error: index out of range
panic during panic

runtime stack:
runtime.throw(0x2aaac61320f2, 0x12)
        /go/src/runtime/panic.go:1117 +0x4c
runtime.panicCheck1(0x2aaac5f28a6c, 0x2aaac61320f2, 0x12)
        /go/src/runtime/panic.go:34 +0xb4
runtime.goPanicIndex(0x2d, 0x6)
        /go/src/runtime/panic.go:87 +0x34
runtime.funcfile(0x4000138260, 0x4000114240, 0x400000002d, 0x3fff81b301c3, 0x0)
        /go/src/runtime/symtab.go:875 +0xdc
runtime.funcline1(0x4000138260, 0x4000114240, 0x3fff81b301c3, 0x1, 0x0, 0x40001380eb, 0x40001380eb)
        /go/src/runtime/symtab.go:893 +0xe4
runtime.funcline(0x4000138260, 0x4000114240, 0x3fff81b301c3, 0x0, 0x1, 0x0)
        /go/src/runtime/symtab.go:898 +0x38
runtime.gentraceback(0x2aaac5f0c18c, 0x40000316f0, 0x0, 0x4000082480, 0x0, 0x0, 0x64, 0x0, 0x0, 0x0, ...)
        /go/src/runtime/traceback.go:414 +0x958
runtime.traceback1(0x2aaac5f0c18c, 0x40000316f0, 0x0, 0x4000082480, 0x0)
        /go/src/runtime/traceback.go:732 +0xbc
runtime.traceback(0x2aaac5f0c18c, 0x40000316f0, 0x0, 0x4000082480)
        /go/src/runtime/traceback.go:686 +0x3c
runtime.dopanic_m(0x4000082480, 0x2aaac5f0c18c, 0x40000316f0, 0x2aaac5f3aa08)
        /go/src/runtime/panic.go:1310 +0x2f8
runtime.fatalthrow.func1()
        /go/src/runtime/panic.go:1172 +0x4c
runtime.systemstack(0x3fffffff01ff)
        /go/src/runtime/asm_arm64.s:248 +0x98
runtime.mstart()
        /go/src/runtime/proc.go:1246

goroutine 8 [running]:
runtime.systemstack_switch()
        /go/src/runtime/asm_arm64.s:194 +0x8 fp=0x40000316b0 sp=0x40000316a0 pc=0x2aaac5f3a958
runtime.fatalthrow()
        /go/src/runtime/panic.go:1169 +0x38 fp=0x40000316f0 sp=0x40000316b0 pc=0x2aaac5f0c308
runtime.throw(0x2aaac612065e, 0x5)
        /go/src/runtime/panic.go:1117 +0x4c fp=0x4000031720 sp=0x40000316f0 pc=0x2aaac5f0c18c
runtime.sigpanic()
        /go/src/runtime/signal_unix.go:741 +0x228 fp=0x4000031760 sp=0x4000031720 pc=0x2aaac5f21aa8
runtime.newobject(0xc61d6220, 0x0)
        /go/src/runtime/malloc.go:1177 +0x18 fp=0x40000317a0 sp=0x4000031770 pc=0x2aaac5ee7668
fatal error: index out of range
stack trace unavailable
4|HWSTF:/data/local/tmp # ./loader  -o http.o
SIGILL: illegal instruction
PC=0x3fff99a466b0 m=5 sigcode=1
instruction bytes: 0x49 0x0 0x0 0x58 0x20 0x1 0x1f 0xd6 0xd0 0xf8 0xba 0xad 0xaa 0x2a 0x0 0x0

goroutine 1 [running]:
runtime: unknown pc 0x3fff99a466b0
stack: frame={sp:0x40000797f0, fp:0x0} stack=[0x4000078000,0x400007a000)
00000040000796f0:  0000000000000380  0000000000000000
0000004000079700:  00000000000002cc  00000000000002b8
0000004000079710:  00000040004467c8  0000000000000014
0000004000079720:  0000000000000014  0000000000000000
0000004000079730:  0000000000000153  0000016300000000
0000004000079740:  000001770000016a  0000000000000003
0000004000079750:  0000000004000000  0000004000114240
0000004000079760:  000000400016c060  0000004000138d38
0000004000079770:  0000004000138a80  0000000000000000
0000004000079780:  00000040001142c0  00000040001142a8
0000004000079790:  0000004000162380  00002aaaade43b40
00000040000797a0:  0000004000114240  0000000000000010
00000040000797b0:  00002aaaaddb6350 <main.main+1616>  000000400047e000
00000040000797c0:  00002aaaaddb64f8 <main.main+2040>  0000004000478eb0
00000040000797d0:  00002aaaaddc2a53  0000000000000009
00000040000797e0:  0000000000000001  0000000000000001
00000040000797f0: <00002aaaaddb651c <main.main+2076>  0000004000000000
0000004000079800:  00003fff99a46578  0000004000141860
0000004000079810:  00003fff99a46000 <main.(*SimpleHanle).ServeHTTP+0>  0000004000141868
0000004000079820:  0000000000001000  0000004000118800
0000004000079830:  00002aaaadba74f4 <runtime.main+612>  00002aaaade5f6a0 
0000004000079840:  000000400015e3f0  00002aaaaddc2a53
0000004000079850:  0000000000000009  00000040001418e8
0000004000079860:  0000000000000000  000000400004aee0
0000004000079870:  0000000000000001  0000000000000001
0000004000079880:  0000000000000009  00003fff99a46090 <main.main+0>
0000004000079890:  0000000000000000  00002aaaae0619c0
00000040000798a0:  00003fff9989d108  0000000000000000
00000040000798b0:  0000000000000000  0000004000079888
00000040000798c0:  0000000000000000  0000000000000001
00000040000798d0:  0000000000000010  0000000000000000
00000040000798e0:  00002aaaadb80680 <runtime.newobject+48>  000000400004adf0
runtime: unknown pc 0x3fff99a466b0
stack: frame={sp:0x40000797f0, fp:0x0} stack=[0x4000078000,0x400007a000)
00000040000796f0:  0000000000000380  0000000000000000
0000004000079700:  00000000000002cc  00000000000002b8
0000004000079710:  00000040004467c8  0000000000000014
0000004000079720:  0000000000000014  0000000000000000
0000004000079730:  0000000000000153  0000016300000000
0000004000079740:  000001770000016a  0000000000000003
0000004000079750:  0000000004000000  0000004000114240
0000004000079760:  000000400016c060  0000004000138d38
0000004000079770:  0000004000138a80  0000000000000000
0000004000079780:  00000040001142c0  00000040001142a8
0000004000079790:  0000004000162380  00002aaaade43b40
00000040000797a0:  0000004000114240  0000000000000010
00000040000797b0:  00002aaaaddb6350 <main.main+1616>  000000400047e000
00000040000797c0:  00002aaaaddb64f8 <main.main+2040>  0000004000478eb0
00000040000797d0:  00002aaaaddc2a53  0000000000000009
00000040000797e0:  0000000000000001  0000000000000001
00000040000797f0: <00002aaaaddb651c <main.main+2076>  0000004000000000
0000004000079800:  00003fff99a46578  0000004000141860
0000004000079810:  00003fff99a46000 <main.(*SimpleHanle).ServeHTTP+0>  0000004000141868
0000004000079820:  0000000000001000  0000004000118800
0000004000079830:  00002aaaadba74f4 <runtime.main+612>  00002aaaade5f6a0
0000004000079840:  000000400015e3f0  00002aaaaddc2a53
0000004000079850:  0000000000000009  00000040001418e8
0000004000079860:  0000000000000000  000000400004aee0
0000004000079870:  0000000000000001  0000000000000001
0000004000079880:  0000000000000009  00003fff99a46090 <main.main+0>
0000004000079890:  0000000000000000  00002aaaae0619c0
00000040000798a0:  00003fff9989d108  0000000000000000
00000040000798b0:  0000000000000000  0000004000079888
00000040000798c0:  0000000000000000  0000000000000001
00000040000798d0:  0000000000000010  0000000000000000
00000040000798e0:  00002aaaadb80680 <runtime.newobject+48>  000000400004adf0

r0      0x3fff99a46578
r1      0x40000783a0
r2      0x4000079830
r3      0x4000478eb0
r4      0x6e69616d2e6e6961
r5      0x0
r6      0x1
r7      0x3fff99a461a0
r8      0x40000797e0
r9      0x4000022340
r10     0x40
r11     0x3fff99a46280
r12     0x0
r13     0x24
r14     0x400005c000
r15     0x25
r16     0x0
r17     0x0
r18     0xffffffff
r19     0x5
r20     0x400016c090
r21     0x4000079758
r22     0x1
r23     0x0
r24     0x2aaaae0c9274
r25     0x0
r26     0x4000079888
r27     0x7e
r28     0x4000000180
r29     0x0
lr      0x3fff99a460b8
sp      0x40000797f0
pc      0x3fff99a466b0
fault   0x0
2|HWSTF:/data/local/tmp # ./loader  -o http.o
SIGILL: illegal instruction
PC=0x3fff97088650 m=4 sigcode=1
instruction bytes: 0x49 0x0 0x0 0x58 0x20 0x1 0x1f 0xd6 0xd0 0x78 0x64 0xb4 0xaa 0x2a 0x0 0x0

goroutine 1 [running]:
runtime: unknown pc 0x3fff97088650
stack: frame={sp:0x40000797f0, fp:0x0} stack=[0x4000078000,0x400007a000)
00000040000796f0:  0000000000000380  0000000000000000
0000004000079700:  00000000000002cc  00000000000002b8
0000004000079710:  00000040004467c8  0000000000000014
0000004000079720:  0000000000000014  0000000000000000
0000004000079730:  0000000000000150  0000015a00000000
0000004000079740:  0000017100000162  0000000000000003
0000004000079750:  0000000004000000  0000004000114240
0000004000079760:  0000004000154060  00000040001389b8
0000004000079770:  0000004000138700  0000000000000000
0000004000079780:  00000040001142c0  00000040001142a8
0000004000079790:  0000004000162380  00002aaab48dbb40
00000040000797a0:  0000004000114240  0000000000000010
00000040000797b0:  00002aaab484e350 <main.main+1616>  000000400047e000
00000040000797c0:  00002aaab484e4f8 <main.main+2040>  0000004000478ec0
00000040000797d0:  00002aaab485aa53  0000000000000009
00000040000797e0:  0000000000000001  0000000000000001
00000040000797f0: <00002aaab484e51c <main.main+2076>  0000004000000000
0000004000079800:  00003fff970885d8  000000400013a8f0
0000004000079810:  00003fff97088000 <main.main.func1+0>  000000400013a908
0000004000079820:  0000000000001000  0000004000118800
0000004000079830:  00002aaab463f4f4 <runtime.main+612>  00002aaab48f76a0
0000004000079840:  000000400013e3f0  00002aaab485aa53
0000004000079850:  0000000000000009  000000400013a980
0000004000079860:  0000000000000000  000000400004aee0
0000004000079870:  0000000000000001  0000000000000001
0000004000079880:  0000000000000009  00003fff97088170 <main.main+0>
0000004000079890:  0000000000000000  00002aaab4af99c0
00000040000798a0:  00003fff969c0108  0000000000000000
00000040000798b0:  0000000000000000  0000004000079888
00000040000798c0:  0000000000000000  0000000000000001
00000040000798d0:  0000000000000010  0000000000000000
00000040000798e0:  00002aaab4618680 <runtime.newobject+48>  000000400004adf0
runtime: unknown pc 0x3fff97088650
stack: frame={sp:0x40000797f0, fp:0x0} stack=[0x4000078000,0x400007a000)
00000040000796f0:  0000000000000380  0000000000000000
0000004000079700:  00000000000002cc  00000000000002b8
0000004000079710:  00000040004467c8  0000000000000014
0000004000079720:  0000000000000014  0000000000000000
0000004000079730:  0000000000000150  0000015a00000000
0000004000079740:  0000017100000162  0000000000000003
0000004000079750:  0000000004000000  0000004000114240
0000004000079760:  0000004000154060  00000040001389b8
0000004000079770:  0000004000138700  0000000000000000
0000004000079780:  00000040001142c0  00000040001142a8
0000004000079790:  0000004000162380  00002aaab48dbb40
00000040000797a0:  0000004000114240  0000000000000010
00000040000797b0:  00002aaab484e350 <main.main+1616>  000000400047e000
00000040000797c0:  00002aaab484e4f8 <main.main+2040>  0000004000478ec0
00000040000797d0:  00002aaab485aa53  0000000000000009
00000040000797e0:  0000000000000001  0000000000000001
00000040000797f0: <00002aaab484e51c <main.main+2076>  0000004000000000
0000004000079800:  00003fff970885d8  000000400013a8f0
0000004000079810:  00003fff97088000 <main.main.func1+0>  000000400013a908
0000004000079820:  0000000000001000  0000004000118800
0000004000079830:  00002aaab463f4f4 <runtime.main+612>  00002aaab48f76a0
0000004000079840:  000000400013e3f0  00002aaab485aa53
0000004000079850:  0000000000000009  000000400013a980
0000004000079860:  0000000000000000  000000400004aee0
0000004000079870:  0000000000000001  0000000000000001
0000004000079880:  0000000000000009  00003fff97088170 <main.main+0>
0000004000079890:  0000000000000000  00002aaab4af99c0
00000040000798a0:  00003fff969c0108  0000000000000000
00000040000798b0:  0000000000000000  0000004000079888
00000040000798c0:  0000000000000000  0000000000000001
00000040000798d0:  0000000000000010  0000000000000000
00000040000798e0:  00002aaab4618680 <runtime.newobject+48>  000000400004adf0

r0      0x3fff970885d8
r1      0x40000783a0
r2      0x4000079830
r3      0x4000478ec0
r4      0x6e69616d2e6e6961
r5      0x0
r6      0x1
r7      0x3fff97088170
r8      0x40000797e0
r9      0x40000223c0
r10     0x40
r11     0x3fff97088280
r12     0x1
r13     0x1
r14     0x400010dcc0
r15     0x0
r16     0x0
r17     0x0
r18     0xffffffff
r19     0x5
r20     0x4000154090
r21     0x4000079758
r22     0x0
r23     0x0
r24     0x2aaab4b61274
r25     0x1
r26     0x4000079888
r27     0x9
r28     0x4000000180
r29     0x0
lr      0x3fff97088198
sp      0x40000797f0
pc      0x3fff97088650
fault   0x0

**Comment by ssrlxl** [comment]
> 给我复制一个完整的栈，另外告知下系统版本，golang版本， goloader使用的版本.
> 我手头没有现成的android环境，不一定能支持

我今天写了简单的demo， 发现在android下，如果函数的参数市interface, 例如func demo(a interface{})类似，只要访问参数就会出现崩溃，func demo(a ...interface{}) 遍历参数会出现index of range

**Comment by pkujhd** [comment]
@ssrlxl  和这个没关系，问题出来relocate的地方，对于ARM64的长指令重定向有问题. 修复估计需要一段时间

**Comment by pkujhd** [comment]
@ssrlxl ， 问题已经修复，取最新的版本即可

**Comment by ssrlxl** [comment]
> @ssrlxl ， 问题已经修复，取最新的版本即可

验证了，非常感谢，修复很及时，真的太厉害了
