### ISSUE TITLE
panic: unresolve external: `runtime.writeBarrier`

### ISSUE THREAD

**Issue by jimil749** [pkujhd/goloader#32]
I have following "plugin" code that I am trying to load using goloader: [Link to code](https://github.com/jimil749/reva-plugin-benchmark/blob/main/pkg/plugins/goloader/json.go). It has a dependency on another package ([link](https://github.com/jimil749/reva-plugin-benchmark/blob/main/pkg/plugins/goloader/json.go)). On compiling the code, and loading using goloader (as explained in the example, [link]()), it throws following error:
```
panic: unresolve external: runtime.writeBarrier
```
Any clue how to solve this?

**Comment by pkujhd** [comment]
@jimil749 , i can't find your loader code, could you give me more infomations?

**Comment by jimil749** [comment]
Hi, sorry about that! This is the link to loader code: https://github.com/jimil749/reva-plugin-benchmark/blob/2dd5c5a9ad0a54dbfca8ce1bd87db121b442ffa5/main.go. 

And this is the code that I am trying to load: https://github.com/jimil749/reva-plugin-benchmark/blob/2dd5c5a9ad0a54dbfca8ce1bd87db121b442ffa5/pkg/plugins/goloader/json.go

And this is the dependency(the code that is being loaded is dependent on this interface): https://github.com/jimil749/reva-plugin-benchmark/blob/2dd5c5a9ad0a54dbfca8ce1bd87db121b442ffa5/pkg/plugins/goloader/manager/manager.go

**Comment by pkujhd** [comment]
@jimil749, the loader looks ok， Did you strip the code on compile? if you strip it, the loader could not find symbol tables for runtime symbol.

**Comment by jimil749** [comment]
I did not. I just followed this: https://github.com/pkujhd/goloader#examples (4th example) for compiling and loading.

**Comment by pkujhd** [comment]
> I did not. I just followed this: https://github.com/pkujhd/goloader#examples (4th example) for compiling and loading.

i test your code, it runs ok on macosx/amd64. 

if you are not， please give me your runtime env， e.g. os version, golang version.

in addition, you need call main.New replace json.New. if you do not set package name, "main" is default

**Comment by jimil749** [comment]
Ahh ok. I'll test it out once again. 

Still I'll provide the runtime env:
`go version go1.16.4 linux/amd64`

os: Ubuntu 20.04

**Comment by pkujhd** [comment]
> Ahh ok. I'll test it out once again.
> 
> Still I'll provide the runtime env:
> `go version go1.16.4 linux/amd64`
> 
> os: Ubuntu 20.04

i don't repeated your error

```
[jhd@test-centos7-build-2-45 reva-plugin-benchmark]$ go version
go version go1.16.4 linux/amd64
[jhd@test-centos7-build-2-45 reva-plugin-benchmark]$ go build 
[jhd@test-centos7-build-2-45 reva-plugin-benchmark]$ go install github.com/jimil749/reva-plugin-benchmark/pkg/plugins/goloader/manager
[jhd@test-centos7-build-2-45 reva-plugin-benchmark]$ go tool compile -I $GOPATH/pkg/`go env GOOS`_`go env GOARCH` pkg/plugins/goloader/json.go 
[jhd@test-centos7-build-2-45 reva-plugin-benchmark]$ ./reva-plugin-benchmark 
<nil>
&{users:[0xc000022080 0xc000022100 0xc000022180 0xc000022200]}[jhd@test-centos7-build-2-45 reva-plugin-benchmark]$ 
[jhd@test-centos7-build-2-45 reva-plugin-benchmark]$ git status
# 头指针分离于 2dd5c5a
[jhd@test-centos7-build-2-45 reva-plugin-benchmark]$ 
```

**Comment by jimil749** [comment]
Hi @pkujhd! Thanks for the quick response. I tested this out again locally. Seems to be working. 

I think the problem occurs when I directly do `go run main.go`. if i build the go binary first and then execute the loader, it works fine! But when I `go run` or even try to run benchmarks using `go test -bench=.`, it seems to panic!

**Comment by pkujhd** [comment]
> ujhd! Thanks for the quick response. I tested this out again locally. Seems to be working.
> 
> I think the problem occurs when I directly do `go run main.go`. if i build the go binary first and then execute the loader, it works fine! But when I `go run` or even try to run benchmarks using `go test -bench=.`, it seems to panic!

not support this used. when used `go run` on linux, the go used compile argument `-s -w`

```
mkdir -p $WORK/b001/exe/
cd .
/home/jhd/programs/go/pkg/tool/linux_amd64/link -o $WORK/b001/exe/main -importcfg $WORK/b001/importcfg.link -s -w -buildmode=exe -buildid=jmj3QMtnxUCnJO6fpCDt/0di_CXuKEyWJQkQN8UnQ/BuKplcEFQ7e9fQTeY9ic/jmj3QMtnxUCnJO6fpCDt -extld=gcc /home/jhd/.cache/go-build/c3/c3d53a237e452409beb3f013ed97318a20d9a9b758c9e5f52944b953c10b2054-d
$WORK/b001/exe/main
unresolve external:runtime.zerobase
fails in loading
panic: unresolve external:runtime.zerobase

goroutine 1 [running]:
main.main()
        /home/jhd/go/src/github.com/jimil749/reva-plugin-benchmark/main.go:46 +0x69c
exit status 2
[jhd@test-centos7-build-2-45 reva-plugin-benchmark]$ go run -x -v -work main.go
```
