### ISSUE TITLE
not support code:[182 13]!]

### ISSUE THREAD

**Issue by ssrlxl** [pkujhd/goloader#33]
环境 ：go: 1.16.2
          windows 10

同样的代码在linux和android都测试过了，唯独windows下出现该情况，注释掉not support code对应代码，程序是可以正常运行

**Comment by pkujhd** [comment]
@ssrlxl  给出testcase

**Comment by pkujhd** [comment]
@ssrlxl ,  如果有更新信息，reopen这个issue
