### ISSUE TITLE
Load error: symName:type.*[]uint8 offset:-1548041450528 is overflow!

### ISSUE THREAD

**Issue by ssrlxl** [pkujhd/goloader#36]
环境信息:
              go: 1.16
             os : win10
更新到6月22号提交的代码，使用examples的schedule测试代码运行报错:
      Load error: symName:type.*[]uint8 offset:-1548041450528 is overflow!
其他的example也是类似的错误

**Comment by pkujhd** [comment]
@ssrlxl , fix #34的时候引入的问题
