### ISSUE TITLE
Not test on arm

### ISSUE THREAD

**Issue by pkujhd** [pkujhd/goloader#4]

**Comment by hepking** [comment]
Thanks！

**Comment by pkujhd** [comment]
arm 32bit exist bug for readobj https://github.com/golang/go/issues/21817, in golang version 1.8 1.0

**Comment by pkujhd** [comment]
https://github.com/pkujhd/goloader/commit/5fe630af04f319d1980135e13f62cf02ca3fb458 support arm 1.10-1.14, test on linux qemu raspberry pi3.
golang 1.8-1.9 readobj have bugs on ARM, so not support.
