### ISSUE TITLE
项目运行不起来

### ISSUE THREAD

**Issue by lyh1091106900** [pkujhd/goloader#40]
哪里能获取到 cmd/objfile/sys，其它地方的代码也依赖cmd下的代码
`package goloader

import (
	"cmd/objfile/sys"
	"fmt"
)

func (linker *Linker) _addDeferReturn(_func *_func) (err error) {
	funcname := gostringnocopy(&linker.pclntable[_func.nameoff])
	Func := linker.symMap[funcname].Func
	if Func != nil && len(Func.FuncData) > _FUNCDATA_OpenCodedDeferInfo {
		sym := linker.symMap[funcname]
		for _, r := range sym.Reloc {
			if r.Sym == linker.symMap[RuntimeDeferReturn] {
				//../cmd/link/internal/ld/pcln.go:pclntab
				switch linker.Arch.Name {
				case sys.Arch386.Name, sys.ArchAMD64.Name:
					_func.deferreturn = uint32(r.Offset) - uint32(sym.Offset) - 1
				case sys.ArchARM.Name, sys.ArchARM64.Name:
					_func.deferreturn = uint32(r.Offset) - uint32(sym.Offset)
				default:
					err = fmt.Errorf("not support arch:%s", linker.Arch.Name)
				}
				break
			}
		}
	}
	return err
}
`

**Comment by pkujhd** [comment]
读README

First, execute the following command, then do build and test. This is because Goloader relies on the internal package, which is forbidden by the Go compiler.

cp -r $GOROOT/src/cmd/internal $GOROOT/src/cmd/objfile
