### ISSUE TITLE
how to debug in Vscode

### ISSUE THREAD

**Issue by lyh1091106900** [pkujhd/goloader#42]
how can I make lauch.json to debug as run cmd code as "./loader -o schedule.o -run main.main -times 10"

**Comment by pkujhd** [comment]
> -o schedule.o -run main.main -times 10

just like this
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}/../examples/loader",
            "args": [
                "-o",
                "YOURPATH/base.o",
            ]
        }
    ]
}
```

**Comment by yedemon** [comment]
这个样子似乎能起来, 但是也跟不进 .o 里面调用的函数里. 估计调试插件的时候, 只能直接运行插件,或者打log了.

**Comment by pkujhd** [comment]
> 这个样子似乎能起来, 但是也跟不进 .o 里面调用的函数里. 估计调试插件的时候, 只能直接运行插件,或者打log了.

这个估计需要看下dlv的源代码，看他对于plugin怎么去读的moduledata，可能会无法支持.

**Comment by pkujhd** [comment]
@lyh1091106900 , 抽空看了下dlv的实现，dlv读取.so文件来填充调试信息，并且在gdb的next时执行ElfUpdateSharedObjects来更新新加载的.so文件（只在linux环境下生效，mac目前不支持），所以目前的goloader无法让dlv取到fileno&lineno, 因为dlv并不会去读moduledata中的pclntable来填充这些信息.
