### ISSUE TITLE
basecontext 安装不成功

### ISSUE THREAD

**Issue by rock-go** [pkujhd/goloader#44]
```bash
 go install github.com/pkujhd/goloader/examples/basecontext
```
```bash
PS D:\github.com\goloader> go install github.com/pkujhd/goloader/examples/basecontext
PS D:\github.com\goloader> go env | findstr GOPATH
set GOPATH=C:\Users\Administrator\go
PS D:\github.com\goloader> cd C:
PS C:\Users\Administrator\go\pkg> ls


    目录: C:\Users\Administrator\go\pkg


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2021/11/2     19:33                mod
d-----         2021/9/24     20:05                sumdb


```

**Comment by pkujhd** [comment]
无法复现

```
D:\Code\go\pkg\windows_amd64\github.com\pkujhd\goloader\examples>go env GOPATH
D:\Code\go

D:\Code\go\pkg\windows_amd64\github.com\pkujhd\goloader\examples>dir
 驱动器 D 中的卷是 Program
 卷的序列号是 000D-A362

 D:\Code\go\pkg\windows_amd64\github.com\pkujhd\goloader\examples 的目录

2021/06/23  13:40    <DIR>          .
2021/06/23  13:40    <DIR>          ..
2021/12/08  09:56            41,714 basecontext.a
               1 个文件         41,714 字节
               2 个目录 76,921,180,160 可用字节

D:\Code\go\pkg\windows_amd64\github.com\pkujhd\goloader\examples>go version
go version go1.15 windows/amd64

D:\Code\go\pkg\windows_amd64\github.com\pkujhd\goloader\examples>
```

**Comment by pkujhd** [comment]
如果有更新reopen

**Comment by ningzhenyi** [comment]
![image](https://user-images.githubusercontent.com/26025135/177458526-6f1960ed-cd27-42ab-9ce9-a73b965f9636.png)
我也遇到了安装不成功的问题，是不是版本问题呢？

**Comment by pkujhd** [comment]
> ![image](https://user-images.githubusercontent.com/26025135/177458526-6f1960ed-cd27-42ab-9ce9-a73b965f9636.png) 我也遇到了安装不成功的问题，是不是版本问题呢？ @pkujhd

如果你的GO111MODULE=“”的配置，安装会被hash到一个cache文件里去.

**Comment by ningzhenyi** [comment]
> > ![图片](https://user-images.githubusercontent.com/26025135/177458526-6f1960ed-cd27-42ab-9ce9-a73b965f9636.png)我也遇到了安装不成功的问题，是不是版本问题呢？@pkujhd
> 
> 如果你的GO111MODULE=""的配置，安装会被hash到一个缓存文件里去。

![image](https://user-images.githubusercontent.com/26025135/177487722-0d98ba34-a369-4aab-96aa-6f76803067a0.png)
我修改成auto，也没有生成

**Comment by ningzhenyi** [comment]
也没有看到有.cache目录

**Comment by pkujhd** [comment]
> ```shell
> go install github.com/pkujhd/goloader/examples/basecontext
> ```

在~/.cache目录下

你也可以使用go install -i github.com/pkujhd/goloader/examples/basecontext
这个命令会生成在$GOPATH/pkg/`go env GOOS`_`go env GOARCH` 目录下
