### ISSUE TITLE
基础类型的变量怎么注册呢= =···

### ISSUE THREAD

**Issue by yedemon** [pkujhd/goloader#46]
尝试在inter.go 里面添加

```go
var strdata string = "this is a string text!"
var intdata int = 0
var pintdata *int = &intdata
var uptr unsafe.Pointer = (unsafe.Pointer)(pintdata)

func init() ....
```

再尝试用loader去加载，就会各种抱怨
Load error: type:type.string not found
Load error: type:type.*int not found
Load error: type:type.unsafe.Pointer not found

用 RegType 似乎也不太好用，不知道这种类型的变量该怎么注册呢···

**Comment by pkujhd** [comment]
@yedemon 

```
RegTypes(symPtr, int(0), int8(0), int16(0), int32(0), int64(0),
		uint(0), uint8(0), uint16(0), uint32(0), uint64(0), true, &int0,
		float32(0), float64(0), complex64(0), complex128(0),
		"", []byte{}, []uint{}, []int{}, uintptr(0), make(chan bool, 1), unsafe.Pointer(&symPtr))
```

这些类型按理说你的loader都应该会用到才对

**Comment by yedemon** [comment]
！！！按理说是会用到的，但是它就是不按理出牌没办法呢··· 我再试试你这个看看，

**Comment by yedemon** [comment]
好像加了这个似乎还是抱怨找不到类型，我跟踪了一下，似乎是在  gcdata.go 的

	typeName := linker.objsymbolMap[sym.Name].Type
	if _, ok := linker.objsymbolMap[typeName]; !ok {
		return fmt.Errorf("type:%s not found\n", typeName)
	}

这里报的错。似乎是 symbol is in loader, ignore generate gc data 这里的问题？

**Comment by yedemon** [comment]
emm... 需要补充什么信息么···

**Comment by pkujhd** [comment]
不需要了，global变量的gc有问题，短时间估计修正不了

**Comment by yedemon** [comment]
QωQ··· 好的··· 谢谢大大喏··· 辛苦

**Comment by pkujhd** [comment]
@yedemon  https://github.com/pkujhd/goloader/commit/e9a52b14c8c61c3e9072529c76b8842be6806152 version fix it

**Comment by yedemon** [comment]
谢大神！我回头看一下！
