### ISSUE TITLE
如果我想要调用的函数参数个数和类型不定，应该如何使用？

### ISSUE THREAD

**Issue by zhiguogg** [pkujhd/goloader#50]
![image](https://user-images.githubusercontent.com/50401300/164865827-42983053-7b20-4f0c-88e3-b4954235a582.png)

![image](https://user-images.githubusercontent.com/50401300/164865850-1ad92275-a66a-43c5-9192-692a7da02cd4.png)

如果这个Hello函数参数个数以及类型不定，应该如何使用goloader？

**Comment by pkujhd** [comment]
不行，必须知晓函数签名

**Comment by eh-steve** [comment]
The JIT compiler in #66 will return the function symbols as a `map[string]interface{}` which you can either type switch/type assert on or use reflection to find out the number and types of function in/out args.

**Comment by pkujhd** [comment]
@eh-steve  “.(func([]byte) (interface{}, error)” means you already know function type.

**Comment by eh-steve** [comment]
(Or you can type switch across multiple different function types, or use reflect to check the in/out args and then call it programmatically)
