### ISSUE TITLE
不能进行json反序列化

### ISSUE THREAD

**Issue by zhiguogg** [pkujhd/goloader#51]
![image](https://user-images.githubusercontent.com/50401300/164884300-8344d7f5-9aa3-43e8-99aa-876f50afc781.png)

 执行  ./loader -o hello.o -run main.Hello会报错：

**Load error: unresolve external:encoding/json.Unmarshal**

但是可以进行序列化

**Comment by pkujhd** [comment]
@zhiguogg 说明encoding/json.Unmarshal在你的loader里不存在这个符号，如果你的loader里没有调用过这个函数，那么需要调用goloader.RegTypes来完成注册，具体可以看examples

**Comment by eh-steve** [comment]
The JIT compiler in #66 will be able to import and build external packages for you automatically, so you don't have to register types on the loader side anymore.

See the tests in `jit/jit_test.go` for examples
