### ISSUE TITLE
在运行的golang代码如果使用指针会报错

### ISSUE THREAD

**Issue by Linkangyis** [pkujhd/goloader#58]
比如
var text string
调用&text必报错

**Comment by pkujhd** [comment]
> 比如 var text string 调用&text必报错

请给出一个testcase

**Comment by Linkangyis** [comment]
> > 比如 var text string 调用&text必报错
> 
> 请给出一个testcase

panic: runtime error: invalid memory address or nil pointer dereference

`package main

import (
	"fmt"
)

func Test(a map[int]string)string{
	var text string
	fmt.Scanln(&text)
	fmt.Println(text)
	return text
}`

**Comment by Linkangyis** [comment]
Load error: unresolve external:fmt.Fscanln
原版输出

**Comment by pkujhd** [comment]
> ```go
> Scanln
> ```

需要注册fmt.Scanln
在loader里调用	goloader.RegTypes(symPtr, fmt.Scanln)

**Comment by Linkangyis** [comment]
> @Linkangyis 需要注册fmt.Scanln 在loader里调用 goloader.RegTypes（symPtr， fmt.Scanln）

感谢
