### ISSUE TITLE
Load error: symName:database/sql.(*DB).Close offset:139266851392960 is overflow!

### ISSUE THREAD

**Issue by yinhediyi** [pkujhd/goloader#61]
Load error: symName:database/sql.(*DB).Close offset:139266851392960 is overflow!
Load error: symName:os.(*File).Close offset:138253268967776 is overflow!
Load error: symName:syscall.(*LazyProc).Call offset:138395175218912 is overflow!

golang: 1.18
os: win10

**Comment by pkujhd** [comment]
这是windows上对于R_ADDR的远地址重定向没有处理造成的，linux上强制mmap返回32位的地址避免了这个问题，修复需要一段时间
