### ISSUE TITLE
有一个想法

### ISSUE THREAD

**Issue by Linkangyis** [pkujhd/goloader#64]
go plugin里面好像有方法可以从字符表里面提取函数 可以尝试一下看看能不能从字符表里面读取，从而免去手动注册函数/类型

**Comment by pkujhd** [comment]
> go plugin里面好像有方法可以从字符表里面提取函数 可以尝试一下看看能不能从字符表里面读取，从而免去手动注册函数/类型

现在就是这样的，注册函数的意思是让你的loader里边包含这个函数, 否则没有这个函数的话，符号表里啥都没有
