### ISSUE TITLE
how to use it in other program

### ISSUE THREAD

**Issue by introspection3** [pkujhd/goloader#70]
PS F:\goprjs\study1> go get "github.com/pkujhd/goloader"
github.com/pkujhd/goloader imports
        cmd/objfile/gcprog: package cmd/objfile/gcprog is not in GOROOT (G:\go\src\cmd\objfile\gcprog)
github.com/pkujhd/goloader imports
        cmd/objfile/objfile: package cmd/objfile/objfile is not in GOROOT (G:\go\src\cmd\objfile\objfile)
github.com/pkujhd/goloader imports
        cmd/objfile/sys: package cmd/objfile/sys is not in GOROOT (G:\go\src\cmd\objfile\sys)
github.com/pkujhd/goloader imports
        github.com/pkujhd/goloader/obj imports
        cmd/objfile/archive: package cmd/objfile/archive is not in GOROOT (G:\go\src\cmd\objfile\archive)
github.com/pkujhd/goloader imports
        github.com/pkujhd/goloader/obj imports
        cmd/objfile/goobj: package cmd/objfile/goobj is not in GOROOT (G:\go\src\cmd\objfile\goobj)
github.com/pkujhd/goloader imports
        github.com/pkujhd/goloader/obj imports
        cmd/objfile/objabi: package cmd/objfile/objabi is not in GOROOT (G:\go\src\cmd\objfile\objabi)

module study1

go 1.20

**Comment by pkujhd** [comment]
> PS F:\goprjs\study1> go get "github.com/pkujhd/goloader" github.com/pkujhd/goloader imports cmd/objfile/gcprog: package cmd/objfile/gcprog is not in GOROOT (G:\go\src\cmd\objfile\gcprog) github.com/pkujhd/goloader imports cmd/objfile/objfile: package cmd/objfile/objfile is not in GOROOT (G:\go\src\cmd\objfile\objfile) github.com/pkujhd/goloader imports cmd/objfile/sys: package cmd/objfile/sys is not in GOROOT (G:\go\src\cmd\objfile\sys) github.com/pkujhd/goloader imports github.com/pkujhd/goloader/obj imports cmd/objfile/archive: package cmd/objfile/archive is not in GOROOT (G:\go\src\cmd\objfile\archive) github.com/pkujhd/goloader imports github.com/pkujhd/goloader/obj imports cmd/objfile/goobj: package cmd/objfile/goobj is not in GOROOT (G:\go\src\cmd\objfile\goobj) github.com/pkujhd/goloader imports github.com/pkujhd/goloader/obj imports cmd/objfile/objabi: package cmd/objfile/objabi is not in GOROOT (G:\go\src\cmd\objfile\objabi)
> 
> module study1
> 
> go 1.20

cp -r $GOROOT/src/cmd/internal $GOROOT/src/cmd/objfile

Please refer to README
