### ISSUE TITLE
the usage of `copy2Slice` here seems to be incorrect, PutInt64 should be used instead

### ISSUE THREAD

**Issue by fumeboy** [pkujhd/goloader#78]
https://github.com/pkujhd/goloader/blob/master/relocate.go#LL138C5-L138C5

`copy2Slice` used to copy the 8 bytes from `*addr` to `*addr+7` into the TEXT segment, but the correct approach should be to copy the uint64 value `addr` itself as [8]byte.

**Comment by pkujhd** [comment]
@fumeboy , MOV instructor want to mov addr's content to register, so copy data to register, not addr to register.

**Comment by pkujhd** [comment]
If you encounter a bug，give me a testcase please. thx

**Comment by fumeboy** [comment]
I couldnt submit a PR on my work computer, but I can provide you with a code snippet.

first, write a Go file as our test module. this file will have a  PCREL relocation pointing to a global variable.
```go
package a

var val = 1

func Main() (output int) {
	return val
}

```
 
then change the bool condition here to always be true ( `if true {` ). run it and you can see a panic.
https://github.com/eh-steve/goloader/blob/WIP---Update-github-actions-to-run-tests/relocate.go#L155

and fix it like this :
```go
func (linker *Linker) relocatePCREL(addr uintptr, loc obj.Reloc, segment *segment, relocByte []byte, addrBase int) (err error) {
	byteorder := linker.Arch.ByteOrder

	if true { // offset > 0x7FFFFF || offset < -0x800000
		bytes := relocByte[loc.Offset-2:]
		modrm0 := relocByte[loc.Offset-1]
		opcode := relocByte[loc.Offset-2]
		if opcode == x86amd64MOVcode && loc.Size >= Uint32Size {
			// jump GOT
			copy(bytes, []byte{0xE9, 0x00, 0x00, 0x00, 0x00, 0x90})  // 0xE9 == JMP; 0x90 == NOP

			offset := (segment.codeBase + segment.codeOff) - (addrBase + loc.Offset + loc.Size - 1) // -1 because len([0xE9]), not len([0xE9, 0x00])
			byteorder.PutUint32(relocByte[loc.Offset-1:], uint32(offset))
		} else {
			return fmt.Errorf("not support code:%v!\n", relocByte[loc.Offset-2:loc.Offset])
		}

		{
			var MOV_A1 = []byte{
				0x48, 0xA1, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // MOVQ  *[64 bit address] =>  RAX
			}

			if modrm := (modrm0 & 0b00111000) | 0b11000000; modrm == 0b11000000 { // if mov RAX => RAX
				// MOVQ  *[64 bit address] =>  RAX
				copy(segment.codeByte[segment.codeOff:], MOV_A1) 
				byteorder.PutUint64(segment.codeByte[segment.codeOff+2:], uint64(addr)+uint64(loc.Add))
				segment.codeOff += len(MOV_A1)
			} else { // else mov RAX => other REG
				// push RAX
				segment.codeByte[segment.codeOff] = 0x50 
				segment.codeOff++

				// mov *[64 bit address] =>  RAX
				copy(segment.codeByte[segment.codeOff:], MOV_A1) 
				byteorder.PutUint64(segment.codeByte[segment.codeOff+2:], uint64(addr)+uint64(loc.Add))
				segment.codeOff += len(MOV_A1)

				// MOV RAX => REG
				var MOV_8B = []byte{0x48, 0x8B, 0x00} 
				copy(segment.codeByte[segment.codeOff:], MOV_8B)
				segment.codeByte[segment.codeOff+len(x86amd64replaceMOVQcode)-2] = modrm
				segment.codeOff += len(MOV_8B)

				// pop RAX
				segment.codeByte[segment.codeOff] = 0x58 
				segment.codeOff++
			}

			// JMP back
			copy(segment.codeByte[segment.codeOff:], []byte{0xff, 0x25, 0x00, 0x00, 0x00, 0x00})
			segment.codeOff += 6
			putAddressAddOffset(byteorder, segment.codeByte, &segment.codeOff, uint64(addrBase+loc.Offset+loc.Size))
		}
	}
	return err
}
```

**Comment by eh-steve** [comment]
On my fork there is indeed some faulty arithmetic in the jump addresses in these PCREL relocs - hopefully working on a proper fix soon. @pkujhd is correct though in that the value at the address is what we need to copy for a 0x8B MOV...

**Comment by pkujhd** [comment]
> On my fork there is indeed some faulty arithmetic in the jump addresses in these PCREL relocs - hopefully working on a proper fix soon. @pkujhd is correct though in that the value at the address is what we need to copy for a 0x8B MOV...

@eh-steve 
maybe faulty arithmetic is use jmp short/near instruction, the offset doesn't minus current instruction offset

**Comment by fumeboy** [comment]
@eh-steve i dont understand why copy `the value at the address` is right. because the value of variable could be change at runtime, if we copy, we only got the initial value.

**Comment by pkujhd** [comment]
> @eh-steve i dont understand why copy `the value at the address` is right. because the value of variable could be change at runtime, if we copy, we only got the initial value.

There may be the problem you mentioned, but the data dealed by the linker is stable data in the runtime， e.g most statements using movQ are used to read os.Stdout.

**Comment by eh-steve** [comment]
@fumeboy There is indeed a problem with the current far address PCREL asm, both in terms of the JMP arithmetic, and the static pointer indirection that used to happen at link time instead of runtime. This would be ok for static values in addresses (e.g. itabs) but not for global variables as your example points out.

I've added a test case for this issue which the upstream currently fails, and completely rewritten the x86 PCREL implementation in this commit to correct both problems: https://github.com/eh-steve/goloader/pull/5/commits/87f559aca3b26419ca2a8ae9e968ac63969e2bef

I've also added x86 `R_GOTPCREL`/`R_TLS_IE` support into the linker (`arm64` still TODO), and enabled `-dynlink` by default in the JIT package, which avoids most (but not all) of these PCREL relocs.

Because not all registers are capable of using the A1 `MOVABS RAX, [add64]` instruction, I've gone with 2 different approaches, one for when the destination register is RAX, and one when it's another arbitrary register (push RAX, read immediate into RAX, then indirect the value into the destination register, then pop RAX).

If you want to give it a try on the tip of that branch, feel free

**Comment by pkujhd** [comment]
@eh-steve @fumeboy  ok, i will port fix to mine repos. thx.

**Comment by fumeboy** [comment]
> I've also added x86 `R_GOTPCREL`/`R_TLS_IE` support into the linker (`arm64` still TODO), and enabled `-dynlink` by default in the JIT package, which avoids most (but not all) of these PCREL relocs.

thanks, and why `not all` ?

**Comment by eh-steve** [comment]
> thanks, and why `not all` ? 

Off the top of my head, strings, float literals, stack tmps, CGo wrappers etc will still use PCRELs not GOT relocs (on the expectation that these symbols would be laid out relatively local to the text)

**Comment by pkujhd** [comment]
@eh-steve， I wirte some test code,  I found some other things, if a global vaiable is not in current package but it is used in loader, use this golobal varable lead to far address problem,  
Almost all instructions need to be processed, not just MOVQ/JMPL
it is a big project.

`package main

import (
	"fmt"

	"github.com/pppa"
)

var a = 1

func main() {
	a = pppa.Val + 1
	a = pppa.Val - 1
	pppa.Test()
	fmt.Println(pppa.Val)
}
`
The above code has been generated INCQ/SUBQ/MOVQ(89)

**Comment by fumeboy** [comment]
I think some problems not necessary to be solved. a safe design should not allow user modules to "write" to global variables outside of their own package. If access to specific global variables is required, it should be specifically injected by the linker like this:

```go
package user_module

var will_be_inject *int // inject the value of `pppa.Val` at linktime

func main() {
  a := *will_be_inject + 1
  a = *will_be_inject - 1
  fmt.Println(*will_be_inject)
}
```

however, this depends on the scene which we want to use goloader.

**Comment by eh-steve** [comment]
@pkujhd I don't think this is a problem in my fork due to both -dynlink avoiding complex PCRELs and mmap_manager guaranteeing a maximum distance. It can build huge packages (http/k8s/gonum) with lots of globals with dependencies from hundreds of packages.

If you share a specific test case I can add it to my tests

**Comment by eh-steve** [comment]
> I think some problems not necessary to be solved. a safe design should not allow user modules to "write" to global variables outside of their own package. If access to specific global variables is required, it should be specifically injected by the linker...

I disagree with this as a goal. I think we should aim to make goloader behave as intuitively to the developer as possible, and that means expecting JIT code to behave the same as if it were compiled into the host binary. I think the way to achieve this is via careful symbol deduplication across packages that are partially included (+itab patching)

**Comment by eh-steve** [comment]
> perhaps we can add a patch to the compiler to make it generate GOT_PCREL for the symbols we specify. it seems not very difficult.

Ideally we wouldn't force the use of GOT for local symbols (e.g stmps/consts) because it will be less efficient code. Also this doesn't address the problem for native CGo code which we can't patch as easily.

Like I said before, I don't think this is a problem (on my fork) so we don't need to do anything, and use of -dynlink alone can't remove the need for mmap manager due to how itab method offsets work in Go

**Comment by fumeboy** [comment]
@eh-steve 

Why does textOff cause problems?

If `R_MethodOff` points to firstmodule, the `off = firstmodule.text - target_addr`
If `R_MethodOff` points to localmodule, the` off = local.text - target_addr`

Even if we want to access the method of the first module from the local module, according to the source code, there doesn't seem to be any problem, right? because the `textOff` function will use the corresponding text segment address to calculate the absolute address.

```go
func (t *_type) textOff(off textOff) unsafe.Pointer {
	if off == -1 {
		// -1 is the sentinel value for unreachable code.
		// See cmd/link/internal/ld/data.go:relocsym.
		return unsafe.Pointer(abi.FuncPCABIInternal(unreachableMethod))
	}
	base := uintptr(unsafe.Pointer(t))
	var md *moduledata
	for next := &firstmoduledata; next != nil; next = next.next {
		if base >= next.types && base < next.etypes {
			md = next
			break
		}
	}
```

**Comment by eh-steve** [comment]
> Why does textOff cause problems?

The case you described is fine (and straightforward).

The problem occurs with types which have unreachable methods.

The base text address is resolved using the module the type is defined in.

If a type is defined in the firstmodule, but it's method is deadcode eliminated as it's unreachable from the host binary, but then the JIT module wants to use this type and method, it has to use the firstmodule type, but the JIT version of the method text which is in the JIT module. This means the type and text are in different modules (which is fine, but the offset between them can only be maximum 32 bits).

stdlib's `plugin` avoids this problem by disabling deadcode elimination for methods entirely as soon as the plugin package is used anywhere (which bloats the host binary).

My approach was to keep types in the firstmodule, but patch their method text offsets to point at text in the JIT module

**Comment by fumeboy** [comment]
> > if DCE will remove the unreachable, why not use type register?
> 
> I don't understand what you mean here

https://github.com/pkujhd/goloader/blob/master/examples/loader/loader.go#L69

use `type register` to keep symbol not be deadcode eliminated

**Comment by eh-steve** [comment]
Yeah you can achieve the same just by doing 
```go
_ = reflect.ValueOf(&sync.WaitGroup)
```

But that requires you to know in advance (in the host binary) everything that might ever be compiled in JIT, which for my use case was impossible (since the JIT code is user-configured). That's why in my fork, this type registration isn't needed at all

**Comment by eh-steve** [comment]
@fumeboy Just to let you know I'm now more happy with the implementation of x86 PCREL relocs in https://github.com/eh-steve/goloader/pull/5, and that branch fixes a bunch of other bugs. There's still [an issue](https://github.com/eh-steve/goloader/issues/11) I'd like to fix before merging, and I'd also like to see all 60 test variations (across OS/arch/+-CGo/+-dynlink) pass if possible

**Comment by eh-steve** [comment]
@pkujhd You copied the wrong version of `x86amd64replaceCALLcode` and `x86amd64replaceCMPLcode` because RAX is used to pass the first arg of a function in the new regabi, and `CMP` needs to indirect RAX (`[RAX]` using `0x38` not `0xf8`). Please make sure you're copying from my latest branch.

**Comment by eh-steve** [comment]
Also you're not pointer aligning the epilogues on arm64 when you're adding a 20 byte `maxExtraCodeSize_ADDRARM64` epilogue. This can cause instruction alignment faults on arm64

**Comment by eh-steve** [comment]
And you're not including the high bit of the destination register from the REX.W prefix in your MOV PCREL rewrite

**Comment by eh-steve** [comment]
There's a bunch more mistakes I think - please look at my master branch and copy from there

**Comment by pkujhd** [comment]
> There's a bunch more mistakes I think - please look at my master branch and copy from there

Thank you for calling attention to my error. I will fix it
