### ISSUE TITLE
`getitab` alloc memory for `itab` by `persistentalloc`, and that couldnt be free

### ISSUE THREAD

**Issue by fumeboy** [pkujhd/goloader#81]
https://github.com/golang/go/blob/96d16803c2aae5407e99c2a1db79bb51d9e1c8da/src/runtime/iface.go#L67

`progToPointerMask` (the function which generate gcmask) also use`persistentalloc`

we cannot solve this memory leak case. I opened this issue just to remind that some memory will still remain in the runtime after the module is unloaded.

**Comment by pkujhd** [comment]
This memory cannot be removed. 
remove itab from itabtable to avoid invalid address errors if it is not allocated to the same block of memory during load the same obj file again.

**Comment by eh-steve** [comment]
Also it's worth noting that this code path is only hit for relatively infrequent dynamic interface assignments (not static ones, where an itab would have been emitted by the compiler and so would be in mmapped memory instead)

**Comment by fumeboy** [comment]
https://github.com/golang/go/blob/3e7ec131667c31448365f47643cf9b58d08ffd26/src/runtime/heapdump.go#L118

another point worth paying attention to, `runtime/debug.WriteHeapDump` will store `*_type` to `typecache`

**Comment by pkujhd** [comment]
> https://github.com/golang/go/blob/3e7ec131667c31448365f47643cf9b58d08ffd26/src/runtime/heapdump.go#L118
> 
> another point worth paying attention to, `runtime/debug.WriteHeapDump` will store `*_type` to `typecache`

This seems to be only used during call heapdump.
*_type is stored in typecache, but it only use pointer for comparison. If the type does not exist, adding it.
it seems does not cause problem, but it retains useless data.

**Comment by eh-steve** [comment]
Yeah, types are only dumped which are currently in the itabtable, so old types that have been cached are never indirected.

**Comment by fumeboy** [comment]
https://github.com/golang/go/blob/a031f4ef83edc132d5f49382bfef491161de2476/src/reflect/type.go#L1558

`reflect`'s lookupCache will also keep pointer to _type, and it is safe to delete.
