### ISSUE TITLE
似乎不支援泛型

### ISSUE THREAD

**Issue by patyhank** [pkujhd/goloader#83]
已經有
``goloader.RegTypes(symPtr, &maths.Vec3d[float64]{})``

但還是會出現 ``unresolve external:maths.(*Vec3d[float64]).Add``

Vec3d是這樣
```go
type Vec3d[T constraints.Float] struct {
	X, Y, Z T
}

func (v Vec3d[T]) Add(vec3d Vec3d[T]) Vec3d[T] {
	return Vec3d[T]{X: v.X + vec3d.X, Y: v.Y + vec3d.Y, Z: v.Z + vec3d.Z}
}
func (v Vec3d[T]) Equals(vec3d Vec3d[T]) bool {
	return v.X == vec3d.X && v.Y == vec3d.Y && v.Z == vec3d.Z
}
```

**Comment by pkujhd** [comment]
@patyhank  给出你的测试环境，在darwin/amd64 golang1.20下未能复现你的错误

**Comment by patyhank** [comment]
linux/amd64 go 1.20.4

**Comment by patyhank** [comment]
有可能是間接使用泛型導致的嗎
因為我並沒有直接使用 maths.(*Vec3d[float64]).Add

**Comment by pkujhd** [comment]
在linux/amd64 golang 1.20中也无法复现你的问题

**Comment by pkujhd** [comment]
> 有可能是間接使用泛型導致的嗎 因為我並沒有直接使用 maths.(*Vec3d[float64]).Add 直接在載入的檔案裡面使用似乎是可行的

能否给出一个testcase

**Comment by patyhank** [comment]
稍等

**Comment by pkujhd** [comment]
这样注册不了，你需要加载rawtest/shared这个包的.a 

goloader.RegTypes(symPtr, []int32{}, math.Floor)
goloader.ReadObjs([]string{"test.o", "/Users/xxx/Library/Caches/go-build/c0/c0617fe178f43e9f56e030c7e5c9fb1a66418b1482c5bbf86a0ef78436a9233f-d"}, []string{"Test", "rawtest/shared"})
修改成这样就可以了

**Comment by patyhank** [comment]
這是泛型才需要這樣的嗎

**Comment by pkujhd** [comment]
> 這是泛型才需要這樣的嗎

不是，interface的也是如此

**Comment by pkujhd** [comment]
如果你有很多依赖在loader中不存在，建议使用https://github.com/eh-steve/goloader/tree/master 这个分支来处理

**Comment by patyhank** [comment]
好的謝謝
