### ISSUE TITLE
Failed to execute plugin which contains dependency `unresolve external:<...>`

### ISSUE THREAD

**Issue by DanijelRadakovic** [pkujhd/goloader#88]
I am using go-loader as my plugin system. The plugin that I want to use is available [here](https://github.com/DanijelRadakovic/ethreum-plugin). I build the object file with following commands as is described in the docs:

```shell
go list -export -f '{{if .Export}}packagefile {{.ImportPath}}={{.Export}}{{end}}' std \
  $(go list -f '{{.Imports}}' ./... \
  | awk '{sub(/^\[/, ""); print }' \
  | awk '{sub(/\]$/, ""); print }') > importcfg
find . -name "*.go" -type f -print | xargs go tool compile -importcfg importcfg -o ethereum.o
``` 

I tried to use that object file in my other [project](https://github.com/DanijelRadakovic/block-explorer) but am I getting the following error:

```shell
go build main.go
./main

unresolve external:github.com/ethereum/go-ethereum/ethclient.(*Client).NetworkID
```

System information:

- Go: 1.20
- OS: Ubuntu 22.04

**Comment by eh-steve** [comment]
Hi, have you tried building/loading a JIT package using my fork https://github.com/eh-steve/goloader ?

**Comment by pkujhd** [comment]
> I am using go-loader as my plugin system. The plugin that I want to use is available [here](https://github.com/DanijelRadakovic/ethreum-plugin). I build the object file with following commands as is described in the docs:

pkujhd/goloader branch not support for obj file with cgo.  you can try eh-steve/goloader branch

`unresolve external:github.com/ethereum/go-ethereum/ethclient.(*Client).NetworkID`
you use a .o not package main, so you  need set path for goloader
