### ISSUE TITLE
//go:linkname lock down future use

### ISSUE THREAD

**Issue by pkujhd** [pkujhd/goloader#98]
on golang >=1.23  will lock down future use linkname
https://github.com/golang/go/issues/67401

this package use linkname access firstmodule and rtype.
open issue follow this change.

**Comment by fumeboy** [comment]
use `checklinkname=0` to keep linkname work ok

**Comment by pkujhd** [comment]
--ldflags="-checklinkname=1" as default value is actived in golang 1.23.rc1

**Comment by pkujhd** [comment]
https://github.com/pkujhd/goloader/commit/c9742ed45689901dafe9b4e731d98fd010792037
